server:
  port: 3344
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yaoguangju/spring-cloud-config
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/