---
spring:
  profiles: dev
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message-service/**
          filters:
            - RewritePath=/message-service/(?<segment>.*), /$\{segment}
        - id: sms-service
          uri: lb://sms-service
          predicates:
            - Path=/sms-service/**
          filters:
            - RewritePath=/sms-service/(?<segment>.*), /$\{segment}
        - id: admin-bff
          uri: lb://admin-bff
          predicates:
            - Path=/admin-bff/**
          filters:
            - RewritePath=/admin-bff/(?<segment>.*), /$\{segment}
        - id: front-bff
          uri: lb://front-bff
          predicates:
            - Path=/front-bff/**
          filters:
            - RewritePath=/front-bff/(?<segment>.*), /$\{segment}
# SpringDoc 的配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 用户服务
        url: /user-service/v3/api-docs
      - name: 订单服务
        url: /order-service/v3/api-docs
      - name: 商品服务
        url: /product-service/v3/api-docs
      - name: 消息服务
        url: /message-service/v3/api-docs
      - name: 短信服务
        url: /sms-service/v3/api-docs
      - name: 后台bff
        url: /admin-bff/v3/api-docs
      - name: 前台bff
        url: /front-bff/v3/api-docs
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

