---
spring:
  profiles: dev
  cloud:
    gateway:
      # 网关的路由规则
      routes:
        # 用户服务的路由
        - id: user-service-route
          uri: lb://user-service # lb:// 指向服务注册中心里的服务名
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1 # 根据你的路径配置决定是否需要
        # 订单服务的路由
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.web: TRACE

# SpringDoc 的配置
# Java 配置类将会动态地填充分组
springdoc:
  swagger-ui:
    urls: [] # 此处留空，由下面的 GroupedOpenApi Bean 动态填充

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

