---
spring:
  profiles: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
logging:
  level:
    org.springframework.web: TRACE

# SpringDoc 的配置
# Java 配置类将会动态地填充分组
springdoc:
  swagger-ui:
    urls: [] # 此处留空，由下面的 GroupedOpenApi Bean 动态填充

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

